apiVersion: v1
kind: Service
metadata:
  name: patient-intake-service
  annotations:
    # THIS IS THE FIX: Tells AWS to make it Public
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    # Ensure your subnets are still listed
    service.beta.kubernetes.io/aws-load-balancer-subnets: "subnet-0cbe18c850ca6d025,subnet-0f19079e8af99ba02"
spec:
  type: LoadBalancer
  selector:
    app: patient-intake
  ports:
    - port: 80
      targetPort: 8888
      nodePort: 30880